version: '3'

vars:
  pnpm_cmd: pnpm
  ray_cli: ray
  extension_name: flow

tasks:
  default:
    desc: List available tasks.
    silent: true
    cmds:
      - task --list

  setup:
    desc: Ensure Raycast CLI and pnpm are available, then install dependencies.
    silent: true
    cmds:
      - |
        set -euo pipefail
        if ! command -v {{.pnpm_cmd}} >/dev/null 2>&1; then
          echo "pnpm not found in PATH."
          echo "Install it from https://pnpm.io/installation and re-run this task."
          exit 1
        fi
        if ! command -v {{.ray_cli}} >/dev/null 2>&1; then
          echo "Raycast CLI '{{.ray_cli}}' not found in PATH."
          echo "Enable it from Raycast via Cmd+K -> \"Enable Command Line\"."
          exit 1
        fi
        {{.pnpm_cmd}} --version >/dev/null
        if [ ! -d node_modules ]; then
          {{.pnpm_cmd}} install
        else
          {{.pnpm_cmd}} install --frozen-lockfile || {{.pnpm_cmd}} install
        fi
        echo "[ok] Flow extension dependencies installed."

  flow:
    desc: Start the Flow Raycast extension in develop mode (passes CLI args through).
    cmds:
      - |
        set -euo pipefail
        if [ ! -d node_modules ]; then
          echo "node_modules missing; running pnpm install..."
          {{.pnpm_cmd}} install
        fi
        {{.pnpm_cmd}} dev{{if .CLI_ARGS}} {{.CLI_ARGS}}{{end}}

  dev:
    desc: Alias for `task flow`.
    silent: true
    cmds:
      - task flow -- {{.CLI_ARGS}}

  run:
    desc: Alias for `task flow`.
    silent: true
    cmds:
      - task flow -- {{.CLI_ARGS}}

  build:
    desc: Build the extension bundle into `dist/`.
    cmds:
      - |
        set -euo pipefail
        {{.pnpm_cmd}} build{{if .CLI_ARGS}} {{.CLI_ARGS}}{{end}}

  lint:
    desc: Run ESLint against the project.
    cmds:
      - |
        set -euo pipefail
        {{.pnpm_cmd}} lint{{if .CLI_ARGS}} {{.CLI_ARGS}}{{end}}

  typecheck:
    desc: Run TypeScript type checking with no emit.
    cmds:
      - |
        set -euo pipefail
        {{.pnpm_cmd}} typecheck{{if .CLI_ARGS}} {{.CLI_ARGS}}{{end}}

  test:
    desc: Run the Vitest suite.
    cmds:
      - |
        set -euo pipefail
        {{.pnpm_cmd}} test{{if .CLI_ARGS}} {{.CLI_ARGS}}{{end}}

  publish:
    desc: Publish the Flow extension via the Raycast API (requires auth).
    cmds:
      - |
        set -euo pipefail
        {{.pnpm_cmd}} publish{{if .CLI_ARGS}} {{.CLI_ARGS}}{{end}}
